### ISSUE TITLE
wsl with ubuntu, vscode and devcontainers just to run this?

### ISSUE THREAD

**Issue by developer992** [microsoft/PubSec-Info-Assistant#531]
then you install powershell into the docker image but there are no ps1 scripts, only bash

this is weird af

This also fails 
`devcontainer build --workspace-folder .`

```
 => ERROR [dev_container_auto_added_stage_label  4/18] RUN bash "/tmp/non-root-user.sh" "vscode" "1000" "1000"                                                                  0.3s
------
 > [dev_container_auto_added_stage_label  4/18] RUN bash "/tmp/non-root-user.sh" "vscode" "1000" "1000":
0.292 /tmp/non-root-user.sh: line 3: $'\r': command not found
0.292 /tmp/non-root-user.sh: line 8: $'\r': command not found
: invalid optionoot-user.sh: line 9: set: -
0.292 set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
0.293 /tmp/non-root-user.sh: line 10: $'\r': command not found
0.293 /tmp/non-root-user.sh: line 20: syntax error near unexpected token `$'do\r''
'.293 /tmp/non-root-user.sh: line 20: `    for CURRENT_USER in ${POSSIBLE_USERS[@]}; do
------
Dockerfile-with-features:17
--------------------
  15 |     # Set up non-root user
  16 |     COPY ./scripts/non-root-user.sh /tmp/
  17 | >>> RUN bash "/tmp/non-root-user.sh" "${USERNAME}" "${USER_UID}" "${USER_GID}"
  18 |
  19 |     # Set env for tracking that we're running in a devcontainer
--------------------
ERROR: failed to solve: process "/bin/sh -c bash \"/tmp/non-root-user.sh\" \"${USERNAME}\" \"${USER_UID}\" \"${USER_GID}\"" did not complete successfully: exit code: 2

View build details: docker-desktop://dashboard/build/default/default/tl5q8t7fddwxqdwzlab1wui6q
Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\primozj\AppData\Local\Temp\devcontainercli\container-features\0.57.0-1709728487580\Dockerfile-with-features -t vsc-aila-eb193efc5bcafdcdb42e6278a371eac7b553067bae904ca59e3e81e59028ef93 --target dev_containers_target_stage --build-arg DOCKER_GROUP_ID= --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\Users\primozj\Documents\Projects\AILAGPT\AILA\AILA\.devcontainer
    at BtA (C:\Users\primozj\AppData\Roaming\npm\node_modules\@devcontainers\cli\dist\spec-node\devContainersSpecCLI.js:465:1933)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Y0 (C:\Users\primozj\AppData\Roaming\npm\node_modules\@devcontainers\cli\dist\spec-node\devContainersSpecCLI.js:464:1841)
    at async IrA (C:\Users\primozj\AppData\Roaming\npm\node_modules\@devcontainers\cli\dist\spec-node\devContainersSpecCLI.js:614:21597)
    at async arA (C:\Users\primozj\AppData\Roaming\npm\node_modules\@devcontainers\cli\dist\spec-node\devContainersSpecCLI.js:614:19422)
{"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\\Users\\primozj\\AppData\\Local\\Temp\\devcontainercli\\container-features\\0.57.0-1709728487580\\Dockerfile-with-features -t vsc-aila-eb193efc5bcafdcdb42e6278a371eac7b553067bae904ca59e3e81e59028ef93 --target dev_containers_target_stage --build-arg DOCKER_GROUP_ID= --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\\Users\\primozj\\Documents\\Projects\\AILAGPT\\AILA\\AILA\\.devcontainer","description":"An error occurred building the image."}
```

**Comment by developer992** [comment]
like we need more proof that microsoft hates python

cant even decide on what os to support

**Comment by developer992** [comment]
learn what poetry is and how to write multi stage docker files

**Comment by developer992** [comment]
and then this happens

![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/149699593/ebc3e288-d5b2-4b63-a860-df7f679c72db)

honestly why would it work,. right

**Comment by developer992** [comment]
PLEASE HIRE SOME PYTHON SENIORS THIS APP IS RETARDED
