### ISSUE TITLE
Issue with redeploying older version v1.1.1

### ISSUE THREAD

**Issue by PaulineJaquot** [microsoft/PubSec-Info-Assistant#884]
We have deployed v1.2 and started testing the retrieval quality of the system. Curiously, the search engine appeared a bit less efficient than the previous one with v1.1.1 (output less complete). We wanted to redeploy v1.1.1 to better compare the two versions, however we no longer managed to do so and got the error below (module uvicorn missing). 

Is there still a way to redeploy that version?

2024-10-08T08:55:32.280497111Z Documentation: http://aka.ms/webapp-linux
2024-10-08T08:55:32.280499611Z Python 3.10.14
2024-10-08T08:55:32.280502011Z Note: Any data outside '/home' is not persisted
2024-10-08T08:55:35.000315781Z Starting OpenBSD Secure Shell server: sshd.
2024-10-08T08:55:35.051545460Z WEBSITES_INCLUDE_CLOUD_CERTS is not set to true.
2024-10-08T08:55:35.300902834Z Site's appCommandLine: gunicorn --workers 2 --worker-class uvicorn.workers.UvicornWorker app:app --timeout 600
2024-10-08T08:55:35.320081201Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite -userStartupCommand 'gunicorn --workers 2 --worker-class uvicorn.workers.UvicornWorker app:app --timeout 600'
2024-10-08T08:55:35.618973048Z Could not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
2024-10-08T08:55:35.639077119Z Could not find operation ID in manifest. Generating an operation id...
2024-10-08T08:55:35.639092819Z Build Operation ID: 984c089c-408b-4ffa-b196-d083b6a2aa55
2024-10-08T08:55:37.241565332Z Oryx Version: 0.2.20240619.2, Commit: cf006407a02b225f59dccd677986973c7889aa50, ReleaseTagName: 20240619.2
2024-10-08T08:55:37.279357665Z Writing output script to '/opt/startup/startup.sh'
2024-10-08T08:55:37.381494123Z WARNING: Could not find virtual environment directory /home/site/wwwroot/antenv.
2024-10-08T08:55:37.390065053Z WARNING: Could not find package directory /home/site/wwwroot/__oryx_packages__.
2024-10-08T08:55:38.661031005Z
2024-10-08T08:55:38.661098705Z Error: class uri 'uvicorn.workers.UvicornWorker' invalid or not found:
2024-10-08T08:55:38.661104305Z
2024-10-08T08:55:38.661107405Z [Traceback (most recent call last):
2024-10-08T08:55:38.661110005Z   File "/opt/python/3.10.14/lib/python3.10/site-packages/gunicorn/util.py", line 111, in load_class
2024-10-08T08:55:38.661112905Z     mod = importlib.import_module('.'.join(components))
2024-10-08T08:55:38.661115405Z   File "/opt/python/3.10.14/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-10-08T08:55:38.661118105Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-10-08T08:55:38.661120705Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-10-08T08:55:38.661123505Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-10-08T08:55:38.661137005Z   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
2024-10-08T08:55:38.661139705Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-10-08T08:55:38.661142305Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-10-08T08:55:38.661144805Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-10-08T08:55:38.661152005Z   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
2024-10-08T08:55:38.661154605Z ModuleNotFoundError: No module named 'uvicorn'
2024-10-08T08:55:38.661157205Z ]
2024-10-08T08:55:38.662068408Z
2024-10-08T08:55:47.019Z INFO  - Container infoasst-web-xbszk_0_97e18414_middleware for site infoasst-web-xbszk initialized successfully and is ready to serve requests.
2024-10-08T08:55:47.191Z ERROR - Container infoasst-web-xbszk_0_97e18414 didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.
2024-10-08T08:55:47.241Z INFO  - Stopping site infoasst-web-xbszk because it failed during startup.

**Comment by dayland** [comment]
You can redeploy v1.1.1 by using the release label in GitHub (https://github.com/microsoft/PubSec-Info-Assistant/tree/v1.1.1). If you open a new codespace at this label you can get the v1.1.1 base to deploy from.

**Comment by bjakems** [comment]
For 1.1.1, are you deploying the version @dayland mentioned?  If possible, please deploy latest of main branch (1.2).

**Comment by dayland** [comment]
This issue is marked for closure due to inactivity for 2 weeks. It will be closed in 5 days.

**Comment by dayland** [comment]
Closing due to inactivity
